In [1]:
import numpy as np
import pandas as pd
import re

import warnings
warnings.filterwarnings('ignore')

1.Demonstrate three different methods for creating identical 2D arrays in NumPy. Provide the code for each method and the final output after each method.

In [2]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array2 = np.zeros((2, 3), dtype=int)
array2[0] = [1, 2, 3]
array2[1] = [4, 5, 6]

In [5]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
array3 = np.full((2, 3), 0)
array3[0] = [1, 2, 3]
array3[1] = [4, 5, 6]

In [7]:
array3

array([[1, 2, 3],
       [4, 5, 6]])

2.Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 100 and Reshape that 1D array into a 2D array.

In [8]:
array =np.linspace(1,100,100)
array

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [9]:
a=array.reshape((10,10))

In [10]:
array.ndim

1

In [11]:
a.ndim

2

3. Explain the following terms.
a. The difference in np.array, np.asarray and np.asanyarray.
b. The difference between Deep copy and shallow copy.

np.array
Use thi when you want to ensure a new array is created, even if it means copying data from an existing array.

In [14]:
arr = np.array([1, 2, 3], copy=True)
arr

array([1, 2, 3])

np.asarray
Use this when you want to convert an input to a NumPy array but avoid unnecessary copying if the input is already an array.

In [15]:
existing_array = np.array([1, 2, 3])
new_array = np.asarray(existing_array)
new_array

array([1, 2, 3])

np.asanyarray
Use this when you want to ensure that subclasses of np.ndarray (e.g., custom array subclasses) are preserved.

In [18]:
class MyArray(np.ndarray): pass

custom_array = MyArray([1, 2, 3])
new_array1 = np.asanyarray(custom_array)
new_array1

MyArray([[[0.00000000e+000, 0.00000000e+000, 1.13149397e-311],
          [1.13149397e-311, 9.88131292e-323, 2.51973479e-322]]])

shallow_copy
Creates a new object, but if the original object has other objects inside it, it only copies the references to those inside objects.

In [19]:
import copy
original_list = [1, 2, [3, 4]]
shallow_copy = copy.copy(original_list)

shallow_copy[2][0] = 99
print(original_list) 

[1, 2, [99, 4]]


Deep Copy
Creates a new object and also creates copies of everything inside the original object.

In [20]:
import copy
original_list = [1, 2, [3, 4]]
deep_copy = copy.deepcopy(original_list)

deep_copy[2][0] = 99
print(original_list) 

[1, 2, [3, 4]]


4. Generate a 3x3 array with random floating-point numbers between 5and 20. then, round each number in the array to 2 decimal places.

In [21]:
df4=np.random.uniform(5,21,(3,3))

In [22]:
rounded=np.round(df4,2)

In [23]:
rounded

array([[18.04, 17.25,  7.41],
       [14.52, 12.93, 16.1 ],
       [10.09, 13.33, 14.72]])

5. Create a NumPy array with random integers between 1 and 10 of shape (5,6)). After creating the array
perform the following operations:

 a)Extract all even integers from array.

 b)Extract all odd integers from array

In [24]:
arr=np.random.randint(1,10,(5,6))
even=arr[arr%2==0]
odd=arr[arr%2!=0]

In [25]:
arr

array([[9, 3, 3, 1, 4, 2],
       [1, 9, 3, 7, 7, 2],
       [5, 5, 7, 5, 7, 5],
       [2, 8, 7, 4, 4, 4],
       [8, 7, 9, 7, 1, 5]], dtype=int32)

In [26]:
even

array([4, 2, 2, 2, 8, 4, 4, 4, 8], dtype=int32)

In [28]:
odd

array([9, 3, 3, 1, 1, 9, 3, 7, 7, 5, 5, 7, 5, 7, 5, 7, 7, 9, 7, 1, 5],
      dtype=int32)

6. Create a 3D NumPy array of shape (3,3,3) containing random integers between 1 and 10. Perform the following operations:

 a) Find the indices of the maximum values along each depth level (third axis).

 b) Perform element-wise multiplication of between both array.

In [29]:
d=np.random.randint(1,11,(3,3,3))

In [30]:
d

array([[[ 7,  6,  2],
        [ 2,  3,  1],
        [ 3,  3,  6]],

       [[ 6,  4,  2],
        [10,  1,  1],
        [ 3, 10,  1]],

       [[10,  4,  6],
        [ 4,  8,  6],
        [ 7,  9,  3]]], dtype=int32)

In [31]:
d_max_indes=np.argmax(d,axis=2)

In [32]:
d_max_indes

array([[0, 1, 2],
       [0, 0, 1],
       [0, 1, 1]])

In [33]:
d_mul=d*d

In [34]:
d_mul

array([[[ 49,  36,   4],
        [  4,   9,   1],
        [  9,   9,  36]],

       [[ 36,  16,   4],
        [100,   1,   1],
        [  9, 100,   1]],

       [[100,  16,  36],
        [ 16,  64,  36],
        [ 49,  81,   9]]], dtype=int32)

7. Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data type. Also display the table attributes and data types of each column.

In [35]:
df=pd.read_csv(r"C:\Users\omsin\Downloads\People Data.csv")
df

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email                  Phone Date of birth  \
0              pwarner@example.org           857.139.8239    27-01-2014   
1    fergusonkatherine@example.net                    NaN    26-07-1931   
2              fhoward@example.org          (599)782-0605    25-11-2013   
3            zjohnston@example.com                    NaN    17-11-2012   
4                 elin@example.net     (390)417-1635x3010    15-04-1923   
..                             ...                    ...           ...   
995         lyonsdaisy@example.net           021.775.2933    05-01-1959   
996        dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997         georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998            wanda04@example.net          (915)292-2254    31-08-1971   
999        deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 10 columns]

In [36]:
df['Phone']=df['Phone'].str.replace('[^a-zA-Z0-9]','',regex=True) 

In [37]:
df

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email              Phone Date of birth  \
0              pwarner@example.org         8571398239    27-01-2014   
1    fergusonkatherine@example.net                NaN    26-07-1931   
2              fhoward@example.org         5997820605    25-11-2013   
3            zjohnston@example.com                NaN    17-11-2012   
4                 elin@example.net    3904171635x3010    15-04-1923   
..                             ...                ...           ...   
995         lyonsdaisy@example.net         0217752933    05-01-1959   
996        dariusbryan@example.com  0011497107799x721    06-10-2001   
997         georgechan@example.org  17507744128x33265    13-05-1918   
998            wanda04@example.net         9152922254    31-08-1971   
999        deannablack@example.org   0797525424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 10 columns]

In [38]:
df[['Phone1','xy_phone']]=df['Phone'].str.split('x',n=1,expand=True) #here +17507744128x33265 split the no. indicator is x

In [39]:
df

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email              Phone Date of birth  \
0              pwarner@example.org         8571398239    27-01-2014   
1    fergusonkatherine@example.net                NaN    26-07-1931   
2              fhoward@example.org         5997820605    25-11-2013   
3            zjohnston@example.com                NaN    17-11-2012   
4                 elin@example.net    3904171635x3010    15-04-1923   
..                             ...                ...           ...   
995         lyonsdaisy@example.net         0217752933    05-01-1959   
996        dariusbryan@example.com  0011497107799x721    06-10-2001   
997         georgechan@example.org  17507744128x33265    13-05-1918   
998            wanda04@example.net         9152922254    31-08-1971   
999        deannablack@example.org   0797525424x67259    24-01-1947   

                           Job Title  Salary         Phone1 xy_phone  
0                  Probation officer   90000     8571398239     None  
1                             Dancer   80000            NaN      NaN  
2                               Copy   50000     5997820605     None  
3           Counselling psychologist   65000            NaN      NaN  
4                Biomedical engineer  100000     3904171635     3010  
..                               ...     ...            ...      ...  
995                Personnel officer   90000     0217752933     None  
996          Education administrator   50000  0011497107799      721  
997  Commercial/residential surveyor   60000    17507744128    33265  
998                 Ambulance person  100000     9152922254     None  
999       Nurse, learning disability   90000     0797525424    67259  

[1000 rows x 12 columns]

In [40]:
df = df.dropna(subset=['Phone'])

In [41]:
df

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
5        6  aF75e6dDEBC5b66     Sherry  Caldwell    Male   
6        7  efeb05c7Cc94EA3     Ernest   Hoffman    Male   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                       Email              Phone Date of birth  \
0        pwarner@example.org         8571398239    27-01-2014   
2        fhoward@example.org         5997820605    25-11-2013   
4           elin@example.net    3904171635x3010    15-04-1923   
5      kaitlin13@example.net         8537800927    06-08-1917   
6     jeffharvey@example.com    0936557480x7895    22-12-1984   
..                       ...                ...           ...   
995   lyonsdaisy@example.net         0217752933    05-01-1959   
996  dariusbryan@example.com  0011497107799x721    06-10-2001   
997   georgechan@example.org  17507744128x33265    13-05-1918   
998      wanda04@example.net         9152922254    31-08-1971   
999  deannablack@example.org   0797525424x67259    24-01-1947   

                           Job Title  Salary         Phone1 xy_phone  
0                  Probation officer   90000     8571398239     None  
2                               Copy   50000     5997820605     None  
4                Biomedical engineer  100000     3904171635     3010  
5          Higher education lecturer   50000     8537800927     None  
6                     Health visitor   60000     0936557480     7895  
..                               ...     ...            ...      ...  
995                Personnel officer   90000     0217752933     None  
996          Education administrator   50000  0011497107799      721  
997  Commercial/residential surveyor   60000    17507744128    33265  
998                 Ambulance person  100000     9152922254     None  
999       Nurse, learning disability   90000     0797525424    67259  

[979 rows x 12 columns]

In [42]:
df['Phone']=df['Phone1'].str.replace(r'\D', '', regex=True).str[-10:]

In [43]:
df

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
5        6  aF75e6dDEBC5b66     Sherry  Caldwell    Male   
6        7  efeb05c7Cc94EA3     Ernest   Hoffman    Male   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                       Email       Phone Date of birth  \
0        pwarner@example.org  8571398239    27-01-2014   
2        fhoward@example.org  5997820605    25-11-2013   
4           elin@example.net  3904171635    15-04-1923   
5      kaitlin13@example.net  8537800927    06-08-1917   
6     jeffharvey@example.com  0936557480    22-12-1984   
..                       ...         ...           ...   
995   lyonsdaisy@example.net  0217752933    05-01-1959   
996  dariusbryan@example.com  1497107799    06-10-2001   
997   georgechan@example.org  7507744128    13-05-1918   
998      wanda04@example.net  9152922254    31-08-1971   
999  deannablack@example.org  0797525424    24-01-1947   

                           Job Title  Salary         Phone1 xy_phone  
0                  Probation officer   90000     8571398239     None  
2                               Copy   50000     5997820605     None  
4                Biomedical engineer  100000     3904171635     3010  
5          Higher education lecturer   50000     8537800927     None  
6                     Health visitor   60000     0936557480     7895  
..                               ...     ...            ...      ...  
995                Personnel officer   90000     0217752933     None  
996          Education administrator   50000  0011497107799      721  
997  Commercial/residential surveyor   60000    17507744128    33265  
998                 Ambulance person  100000     9152922254     None  
999       Nurse, learning disability   90000     0797525424    67259  

[979 rows x 12 columns]

In [44]:
df_filtered=df[df['Phone'].str.len()==10]

In [45]:
df

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
5        6  aF75e6dDEBC5b66     Sherry  Caldwell    Male   
6        7  efeb05c7Cc94EA3     Ernest   Hoffman    Male   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                       Email       Phone Date of birth  \
0        pwarner@example.org  8571398239    27-01-2014   
2        fhoward@example.org  5997820605    25-11-2013   
4           elin@example.net  3904171635    15-04-1923   
5      kaitlin13@example.net  8537800927    06-08-1917   
6     jeffharvey@example.com  0936557480    22-12-1984   
..                       ...         ...           ...   
995   lyonsdaisy@example.net  0217752933    05-01-1959   
996  dariusbryan@example.com  1497107799    06-10-2001   
997   georgechan@example.org  7507744128    13-05-1918   
998      wanda04@example.net  9152922254    31-08-1971   
999  deannablack@example.org  0797525424    24-01-1947   

                           Job Title  Salary         Phone1 xy_phone  
0                  Probation officer   90000     8571398239     None  
2                               Copy   50000     5997820605     None  
4                Biomedical engineer  100000     3904171635     3010  
5          Higher education lecturer   50000     8537800927     None  
6                     Health visitor   60000     0936557480     7895  
..                               ...     ...            ...      ...  
995                Personnel officer   90000     0217752933     None  
996          Education administrator   50000  0011497107799      721  
997  Commercial/residential surveyor   60000    17507744128    33265  
998                 Ambulance person  100000     9152922254     None  
999       Nurse, learning disability   90000     0797525424    67259  

[979 rows x 12 columns]

In [46]:
df_filtered = df_filtered.reset_index(drop=True)

In [47]:
df = df.reset_index(drop=True)

In [48]:
# Copy the 'Phone' column from df_filtered to df
df.loc[df_filtered.index, 'Phone'] = df_filtered['Phone']

In [49]:
# Convert 'Phone' column to integer type
df['Phone'] = pd.to_numeric(df['Phone'], errors='coerce').astype('Int64')

In [50]:
print(df.columns)

Index(['Index', 'User Id', 'First Name', 'Last Name', 'Gender', 'Email',
       'Phone', 'Date of birth', 'Job Title', 'Salary', 'Phone1', 'xy_phone'],
      dtype='object')


In [51]:
pd.Categorical(df['Phone'])

[8571398239, 5997820605, 3904171635, 8537800927, 936557480, ..., 217752933, 1497107799, 7507744128, 9152922254, 797525424]
Length: 979
Categories (944, Int64): [1081, 3086, 9104, 171834, ..., 9961915230, 9970427826, 9971399531, 9974650335]

In [52]:
df

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        3  810Ce0F276Badec     Sheryl    Lowery  Female   
2        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
3        6  aF75e6dDEBC5b66     Sherry  Caldwell    Male   
4        7  efeb05c7Cc94EA3     Ernest   Hoffman    Male   
..     ...              ...        ...       ...     ...   
974    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
975    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
976    998  2adde51d8B8979E      Cathy  Mckinney  Female   
977    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
978   1000  8b756f6231DDC6e        Lee      Tran  Female   

                       Email       Phone Date of birth  \
0        pwarner@example.org  8571398239    27-01-2014   
1        fhoward@example.org  5997820605    25-11-2013   
2           elin@example.net  3904171635    15-04-1923   
3      kaitlin13@example.net  8537800927    06-08-1917   
4     jeffharvey@example.com   936557480    22-12-1984   
..                       ...         ...           ...   
974   lyonsdaisy@example.net   217752933    05-01-1959   
975  dariusbryan@example.com  1497107799    06-10-2001   
976   georgechan@example.org  7507744128    13-05-1918   
977      wanda04@example.net  9152922254    31-08-1971   
978  deannablack@example.org   797525424    24-01-1947   

                           Job Title  Salary         Phone1 xy_phone  
0                  Probation officer   90000     8571398239     None  
1                               Copy   50000     5997820605     None  
2                Biomedical engineer  100000     3904171635     3010  
3          Higher education lecturer   50000     8537800927     None  
4                     Health visitor   60000     0936557480     7895  
..                               ...     ...            ...      ...  
974                Personnel officer   90000     0217752933     None  
975          Education administrator   50000  0011497107799      721  
976  Commercial/residential surveyor   60000    17507744128    33265  
977                 Ambulance person  100000     9152922254     None  
978       Nurse, learning disability   90000     0797525424    67259  

[979 rows x 12 columns]

8. Perform the following tas\s using people dataset:

 a) Read the 'data.csv' file using pandas, skipping the first 50 rows.

 b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

 c) Display the first 10 rows of the filtered dataset.

 d) Extract the ‘Salary’ column as a Series and display its last 5 values.

In [61]:
df2= pd.read_csv(r"C:\Users\omsin\Downloads\People Data.csv",skiprows=50)

In [62]:
df2

50  afF3018e9cdd1dA     George    Mercer  Female  \
0      51  CccE5DAb6E288e5         Jo    Zavala    Male   
1      52  DfBDc3621D4bcec     Joshua     Carey  Female   
2      53  f55b0A249f5E44D     Rickey     Hobbs  Female   
3      54  Ed71DcfaBFd0beE      Robyn    Reilly    Male   
4      55  FDaFD0c3f5387EC  Christina    Conrad    Male   
..    ...              ...        ...       ...     ...   
945   996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
946   997  ECddaFEDdEc4FAB      Donna     Barry  Female   
947   998  2adde51d8B8979E      Cathy  Mckinney  Female   
948   999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
949  1000  8b756f6231DDC6e        Lee      Tran  Female   

    douglascontreras@example.net    +1-326-669-0118x4341  11-09-1941  \
0           pamela64@example.net  001-859-448-9935x54536  23-11-1992   
1      dianashepherd@example.net    001-274-739-8470x814  07-01-1915   
2      ingramtiffany@example.org        241.179.9509x498  01-07-1910   
3     carriecrawford@example.org       207.797.8345x6177  27-07-1982   
4     fuentesclaudia@example.net    001-599-042-7428x143  06-01-1998   
..                           ...                     ...         ...   
945       lyonsdaisy@example.net            021.775.2933  05-01-1959   
946      dariusbryan@example.com    001-149-710-7799x721  06-10-2001   
947       georgechan@example.org   +1-750-774-4128x33265  13-05-1918   
948          wanda04@example.net           (915)292-2254  31-08-1971   
949      deannablack@example.org      079.752.5424x67259  24-01-1947   

             Human resources officer   70000  
0                       Nurse, adult   80000  
1                Seismic interpreter   70000  
2                          Barrister   60000  
3               Engineer, structural  100000  
4                    Producer, radio   50000  
..                               ...     ...  
945                Personnel officer   90000  
946          Education administrator   50000  
947  Commercial/residential surveyor   60000  
948                 Ambulance person  100000  
949       Nurse, learning disability   90000  

[950 rows x 10 columns]

In [63]:
df1= pd.read_csv(r"C:\Users\omsin\Downloads\People Data.csv",usecols=['Last Name', 'Gender', 'Email', 'Phone', 'Salary'])

In [64]:
df1

Last Name  Gender                          Email                  Phone  \
0     Mahoney    Male            pwarner@example.org           857.139.8239   
1      Rivers  Female  fergusonkatherine@example.net                    NaN   
2      Lowery  Female            fhoward@example.org          (599)782-0605   
3      Hooper    Male          zjohnston@example.com                    NaN   
4        Rice  Female               elin@example.net     (390)417-1635x3010   
..        ...     ...                            ...                    ...   
995    Bryant  Female         lyonsdaisy@example.net           021.775.2933   
996     Barry  Female        dariusbryan@example.com   001-149-710-7799x721   
997  Mckinney  Female         georgechan@example.org  +1-750-774-4128x33265   
998    Phelps    Male            wanda04@example.net          (915)292-2254   
999      Tran  Female        deannablack@example.org     079.752.5424x67259   

     Salary  
0     90000  
1     80000  
2     50000  
3     65000  
4    100000  
..      ...  
995   90000  
996   50000  
997   60000  
998  100000  
999   90000  

[1000 rows x 5 columns]

In [65]:
df1.head(10)

Last Name  Gender                          Email               Phone  Salary
0   Mahoney    Male            pwarner@example.org        857.139.8239   90000
1    Rivers  Female  fergusonkatherine@example.net                 NaN   80000
2    Lowery  Female            fhoward@example.org       (599)782-0605   50000
3    Hooper    Male          zjohnston@example.com                 NaN   65000
4      Rice  Female               elin@example.net  (390)417-1635x3010  100000
5  Caldwell    Male          kaitlin13@example.net          8537800927   50000
6   Hoffman    Male         jeffharvey@example.com   093.655.7480x7895   60000
7  Andersen    Male           alicia33@example.org          4709522945   65000
8      Mays    Male             jake50@example.com        013.820.4758   50000
9  Mitchell    Male      lanechristina@example.net  (560)903-5068x4985   50000

In [66]:
df1['Salary'].tail(5)

995     90000
996     50000
997     60000
998    100000
999     90000
Name: Salary, dtype: int64

9.Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Duke', 'Gender' column contains the word Female and ‘Salary’ should be less than 85000

In [67]:
df[(df['Salary']<85000)& (df['Last Name']=='Duke')&(df['Gender']=='Female')]

Index          User Id First Name Last Name  Gender  \
39      46  99A502C175C4EBd     Olivia      Duke  Female   
193    211  DF17975CC0a0373    Katrina      Duke  Female   
437    458  dcE1B7DE83c1076      Traci      Duke  Female   
708    730  c9b482D7aa3e682     Lonnie      Duke  Female   

                        Email       Phone Date of birth        Job Title  \
39        diana26@example.net  3664758607    13-10-1934          Dentist   
193       robin78@example.com  5003439851    21-09-1935  Producer, radio   
437  perryhoffman@example.org  6119514635    11-02-1997        Herbalist   
708   kevinkramer@example.net  4338092376    12-05-2015     Nurse, adult   

     Salary         Phone1 xy_phone  
39    60000  0013664758607    04350  
193   50000     7404340212     None  
437   50000    19035960995      489  
708   70000     9826926257     None

10. Create a 7*5 Dataframe in Pandas using a series generated from 35 random integers between 1 to 6?

In [80]:
data = pd.Series(np.random.randint(1,7,size=35))

In [81]:
data

0     3
1     6
2     5
3     4
4     1
5     3
6     1
7     1
8     4
9     6
10    6
11    3
12    2
13    3
14    2
15    1
16    1
17    1
18    2
19    1
20    5
21    2
22    2
23    5
24    1
25    3
26    6
27    3
28    4
29    1
30    5
31    4
32    4
33    3
34    4
dtype: int32

In [86]:
data_array = np.array(data).reshape(7, 5)

In [88]:
df3 = pd.DataFrame(data_array, columns=[f'col{i+1}' for i in range(5)])

In [89]:
df3

col1  col2  col3  col4  col5
0     3     6     5     4     1
1     3     1     1     4     6
2     6     3     2     3     2
3     1     1     1     2     1
4     5     2     2     5     1
5     3     6     3     4     1
6     5     4     4     3     4

11. Create two different Series, each of length 50, with the following criteria:

a) The first Series should contain random numbers ranging from 10 to 50.

b) The second Series should contain random numbers ranging from 100 to 1000.

c) Create a DataFrame by joining these Series by column, and, change the names of the columns to 'col1', 'col2',etc

In [90]:
series1=pd.Series(np.random.randint(10,51,size=50))

In [92]:
series1

0     24
1     30
2     25
3     27
4     45
5     35
6     46
7     43
8     23
9     11
10    30
11    50
12    17
13    23
14    47
15    30
16    37
17    23
18    14
19    48
20    41
21    13
22    30
23    15
24    49
25    32
26    34
27    18
28    27
29    42
30    37
31    24
32    31
33    49
34    44
35    32
36    30
37    44
38    47
39    37
40    50
41    32
42    11
43    43
44    40
45    36
46    28
47    40
48    11
49    23
dtype: int32

In [91]:
series2=pd.Series(np.random.randint(100,1001,size=50))

In [93]:
series2

0     422
1     520
2     400
3     105
4     764
5     722
6     274
7     238
8     211
9     750
10    175
11    691
12    752
13    196
14    515
15    391
16    344
17    567
18    351
19    903
20    354
21    718
22    282
23    110
24    280
25    664
26    162
27    320
28    113
29    333
30    315
31    250
32    805
33    898
34    345
35    476
36    351
37    434
38    626
39    386
40    852
41    829
42    944
43    552
44    469
45    460
46    375
47    738
48    160
49    297
dtype: int32

In [95]:
df=pd.DataFrame({'col1':series1,'col2':series2})
df

col1  col2
0     24   422
1     30   520
2     25   400
3     27   105
4     45   764
5     35   722
6     46   274
7     43   238
8     23   211
9     11   750
10    30   175
11    50   691
12    17   752
13    23   196
14    47   515
15    30   391
16    37   344
17    23   567
18    14   351
19    48   903
20    41   354
21    13   718
22    30   282
23    15   110
24    49   280
25    32   664
26    34   162
27    18   320
28    27   113
29    42   333
30    37   315
31    24   250
32    31   805
33    49   898
34    44   345
35    32   476
36    30   351
37    44   434
38    47   626
39    37   386
40    50   852
41    32   829
42    11   944
43    43   552
44    40   469
45    36   460
46    28   375
47    40   738
48    11   160
49    23   297

12. Perform the following operations using people data set:

a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.
b) Delete the rows containing any missing values.
c) Print the final output also.

In [100]:
df9= pd.read_csv(r"C:\Users\omsin\Downloads\People Data.csv")

In [101]:
df9

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email                  Phone Date of birth  \
0              pwarner@example.org           857.139.8239    27-01-2014   
1    fergusonkatherine@example.net                    NaN    26-07-1931   
2              fhoward@example.org          (599)782-0605    25-11-2013   
3            zjohnston@example.com                    NaN    17-11-2012   
4                 elin@example.net     (390)417-1635x3010    15-04-1923   
..                             ...                    ...           ...   
995         lyonsdaisy@example.net           021.775.2933    05-01-1959   
996        dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997         georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998            wanda04@example.net          (915)292-2254    31-08-1971   
999        deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 10 columns]

In [106]:
df9.drop(columns=['Email','Phone','Date of birth'],inplace=True, errors='ignore')
df9

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 7 columns]

In [110]:
df9.dropna(inplace=True)
df9

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 7 columns]

In [111]:
df9

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 7 columns]